# ---Bot Settings---
bot_token: 'MTIxOTM0MzM5NTc4OTYwMjkxNw.GNFnR3._149KVZiGivbNRwKsTeoRJsWtFY9sn52UIu8xY'
bot_status: 'boostup.cc'
guild_ids: [1230970229895729162]


# ---Logs---
hwid_reset_logs_channel: 1231215370791292979