# ---Bot Settings---
bot_token: 'MTE4ODkwNDgzOTIzMzY4MzQ4Ng.GI8fQz.P-lhj0IeOALK-Qhpjyvyist6rLnjTYqwiC9BUU'
bot_status: 'boostup.cc'
guild_ids: [1208491583545024584]


# ---Logs---
hwid_reset_logs_channel: 1188864721101791282