# ---Bot Settings---
bot_token: 'MTE4NTIyNjUyNDkyOTA0NDYxMg.GZv2o0.BBA6TY-CC8rDk-hHhEFhMBPJL-Tuh-lAMe5paw'
bot_status: 'boostup.cc'
guild_ids: [1176226478137036844]


# ---Logs---
hwid_reset_logs_channel: 1176756851581390938