# ---Bot Settings---
bot_token: 'MTE4ODE4NjQ2MzQxODk4NjY1Ng.GSTO8D.fafIPqGVHbWFCXNblAnTmljjMG3TyzaC704Ky0'
bot_status: 'boostup.cc'
guild_ids: [1187688395590344714]


# ---Logs---
hwid_reset_logs_channel: 1187691672797200434