# ---Bot Settings---
bot_token: 'MTIxOTM0MzM5NTc4OTYwMjkxNw.GNFnR3._149KVZiGivbNRwKsTeoRJsWtFY9sn52UIu8xY'
bot_status: 'boostup.cc'
guild_ids: [1212733196467441734]


# ---Logs---
hwid_reset_logs_channel: 1213049446070353921